FROM node:20-slim

WORKDIR /app

COPY package.json ./
RUN npm install --omit=dev

COPY server.js ./server.js
COPY public ./public

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080
CMD ["npm", "run", "start"]